package com.ibkglobal.integrator.engine.builder;

public enum RouteType {
	MCA_DEFAULT_ADAPTER_IN,
	MCA_DEFAULT_ADAPTER_OUT,
	MCA_INBOUND,
	MCA_BID_PROCESS,  
	MCA_HEALTH_CHECK,
	MCA_BID_ADAPTER,
	MCA_LOCAL_ADAPTER_OUT,
	
	FEP_DEFAULT_ADAPTER_IN,
	FEP_DEFAULT_ADAPTER_OUT,
	FEP_LOCAL_ADAPTER_OUT,
	
	EAI_DEFAULT_ADAPTER_IN,
	EAI_DEFAULT_ADAPTER_OUT,
	EAI_INBOUND,
	EAI_BATCH_ADAPTER_IN,
	
	API_DEFAULT_ADAPTER_IN,
	API_REST_ADAPTER_IN,
	API_DEFAULT_ADAPTER_OUT,
	API_INBOUND,
	
	CUSTOM
}