package com.ibkglobal.common.repository;

public enum CacheType {
	// MCA
	IBK_MCA_INTERFACE,
	
	// EAI
	IBK_EAI_INTERFACE,
	IBK_EAI_INTERFACE_KEY,
	
	// MCA / EAI Common
	IBK_SOURCE_IO,
	IBK_TARGET_IO,
	IBK_MAPPING_IN,
	IBK_MAPPING_OUT,
	
	// FEP
	IBK_FEP_INTERFACE_EXT_INFO,
	IBK_FEP_INTERFACE_KEY,
	IBK_FEP_MESSAGE,
	IBK_FEP_HEADER_MESSAGE,
	IBK_FEP_UNIT,
	IBK_FEP_MAPPING,
	
	// FEPADMIN
	IBK_FEP_RECV_MSG,
	
	//API
	IBK_API_INTERFACE,
}
